name: Build docker image with dev tag and publish compose as OCI artefact on PR to main

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["workflow-2"]
    types: [completed]

jobs:
  build-and-push:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build docker image
        working-directory: ./docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:dev -f Dockerfile ..
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:dev
          
      - name: Publish docker-compose-dev.yml
        working-directory: ./docker
        run: |
          docker compose -f docker-compose-dev.yml publish ${{ secrets.DOCKERHUB_USERNAME }}/easymatch-compose:dev --with-env -y