name: Publish compose as OCI artefact on Release

on:
  release:
    types: [published]  

jobs:
   publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        id: release

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build docker image
        working-directory: ./docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:${{ steps.release.outputs.TAG }} -f Dockerfile ..
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:${{ steps.release.outputs.TAG }}

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:${{ steps.release.outputs.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/easymatch:latest

      - name: Publish docker-compose.yml
        working-directory: ./docker
        run: |
          sed -i "s|easymatch:[^ ]*|easymatch:${{ steps.release.outputs.TAG }}|g" docker-compose.yml
          docker compose -f docker-compose.yml publish ${{ secrets.DOCKERHUB_USERNAME }}/easymatch-compose:${{ steps.release.outputs.TAG }} --with-env=true < <(printf "y\n")
          docker compose -f docker-compose.yml publish ${{ secrets.DOCKERHUB_USERNAME }}/easymatch-compose:latest --with-env=true < <(printf "y\n")